"""Shared project state layer (Phase 2).

Exposes the `AHSEAState` root model, its constituent Pydantic models, and
the safe operation helpers used to mutate it.
"""

from app.state.enums import (
    AgentStatus,
    AgentType,
    ArtifactType,
    ContractType,
    DeploymentStage,
    ErrorSeverity,
    EventLevel,
    RequirementPriority,
    RequirementStatus,
    SystemAgentKind,
    TaskComplexity,
    TaskStatus,
    TestOutcome,
)
from app.state.models import (
    AgentDefinition,
    AgentEvent,
    AgentRuntimeStatus,
    AHSEAState,
    APIContract,
    ArchitectureDecision,
    ArchitectureState,
    Artifact,
    Contract,
    DatabaseContract,
    DeploymentState,
    EnvironmentContract,
    ErrorRecord,
    Module,
    ProjectEvent,
    ProjectMetadata,
    QAReport,
    Requirement,
    Task,
    TaskDependency,
    TaskResult,
    Technology,
    TestResult,
)
from app.state.operations import (
    StateError,
    add_agent,
    add_artifact,
    add_contract,
    add_error,
    add_event,
    add_task,
    get_blocked_tasks,
    get_ready_tasks,
    mark_task_completed,
    mark_task_failed,
    update_agent_status,
    update_task,
)

__all__ = [
    # enums
    "AgentStatus",
    "AgentType",
    "ArtifactType",
    "ContractType",
    "DeploymentStage",
    "ErrorSeverity",
    "EventLevel",
    "RequirementPriority",
    "RequirementStatus",
    "SystemAgentKind",
    "TaskComplexity",
    "TaskStatus",
    "TestOutcome",
    # models
    "AgentDefinition",
    "AgentEvent",
    "AgentRuntimeStatus",
    "AHSEAState",
    "APIContract",
    "ArchitectureDecision",
    "ArchitectureState",
    "Artifact",
    "Contract",
    "DatabaseContract",
    "DeploymentState",
    "EnvironmentContract",
    "ErrorRecord",
    "Module",
    "ProjectEvent",
    "ProjectMetadata",
    "QAReport",
    "Requirement",
    "Task",
    "TaskDependency",
    "TaskResult",
    "Technology",
    "TestResult",
    # operations
    "StateError",
    "add_agent",
    "add_artifact",
    "add_contract",
    "add_error",
    "add_event",
    "add_task",
    "get_blocked_tasks",
    "get_ready_tasks",
    "mark_task_completed",
    "mark_task_failed",
    "update_agent_status",
    "update_task",
]
