"""initial schema (Phase 17)

Creates every table in the Phase 17 spec: projects, agents, tasks,
artifacts, contracts, events, errors, test_results, deployment_runs,
architecture_decisions, repair_attempts, llm_requests.

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-16 13:28:16.863945

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('idea_prompt', sa.Text(), nullable=False),
    sa.Column('workspace_path', sa.String(length=1024), nullable=True),
    sa.Column('repo_url', sa.String(length=1024), nullable=True),
    sa.Column('default_branch', sa.String(length=200), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_projects'))
    )
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('system_kind', sa.String(length=32), nullable=True),
    sa.Column('parent_agent_id', sa.String(length=64), nullable=True),
    sa.Column('team_name', sa.String(length=200), nullable=True),
    sa.Column('role_description', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('allowed_tools', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_task_id', sa.String(length=64), nullable=True),
    sa.Column('status_message', sa.Text(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_agents_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agents'))
    )
    op.create_index(op.f('ix_agents_project_id'), 'agents', ['project_id'], unique=False)
    op.create_table('architecture_decisions',
    sa.Column('decision_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('context', sa.Text(), nullable=False),
    sa.Column('decision', sa.Text(), nullable=False),
    sa.Column('consequences', sa.Text(), nullable=True),
    sa.Column('alternatives_considered', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_architecture_decisions_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_architecture_decisions'))
    )
    op.create_index(op.f('ix_architecture_decisions_project_id'), 'architecture_decisions', ['project_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('artifact_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('artifact_type', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('produced_by_agent_id', sa.String(length=64), nullable=True),
    sa.Column('produced_by_task_id', sa.String(length=64), nullable=True),
    sa.Column('content_hash', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_artifacts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artifact_id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_project_id'), 'artifacts', ['project_id'], unique=False)
    op.create_table('contracts',
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('contract_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owning_module_id', sa.String(length=64), nullable=True),
    sa.Column('consuming_module_ids', sa.JSON(), nullable=False),
    sa.Column('api', sa.JSON(), nullable=True),
    sa.Column('database', sa.JSON(), nullable=True),
    sa.Column('environment', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_contracts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contract_id', name=op.f('pk_contracts'))
    )
    op.create_index(op.f('ix_contracts_project_id'), 'contracts', ['project_id'], unique=False)
    op.create_table('deployment_runs',
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('last_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('verification_passed', sa.Boolean(), nullable=True),
    sa.Column('rollback_reason', sa.Text(), nullable=True),
    sa.Column('deployment_log', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_deployment_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_deployment_runs'))
    )
    op.create_index(op.f('ix_deployment_runs_created_at'), 'deployment_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_deployment_runs_project_id'), 'deployment_runs', ['project_id'], unique=False)
    op.create_table('errors',
    sa.Column('error_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=200), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_errors_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('error_id', name=op.f('pk_errors'))
    )
    op.create_index(op.f('ix_errors_project_id'), 'errors', ['project_id'], unique=False)
    op.create_table('events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_events_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_events'))
    )
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_project_id'), 'events', ['project_id'], unique=False)
    op.create_table('llm_requests',
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('agent_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('prompt_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_llm_requests_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('request_id', name=op.f('pk_llm_requests'))
    )
    op.create_index(op.f('ix_llm_requests_created_at'), 'llm_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_llm_requests_project_id'), 'llm_requests', ['project_id'], unique=False)
    op.create_table('repair_attempts',
    sa.Column('attempt_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('error_id', sa.String(length=64), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('diagnosis_root_cause', sa.Text(), nullable=True),
    sa.Column('diagnosis_classification', sa.String(length=64), nullable=True),
    sa.Column('diagnosis_responsible_team', sa.String(length=200), nullable=True),
    sa.Column('diagnosis_proposed_solution', sa.Text(), nullable=True),
    sa.Column('diagnosis_confidence', sa.Float(), nullable=True),
    sa.Column('rework_task_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_repair_attempts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id', name=op.f('pk_repair_attempts'))
    )
    op.create_index(op.f('ix_repair_attempts_project_id'), 'repair_attempts', ['project_id'], unique=False)
    op.create_index(op.f('ix_repair_attempts_task_id'), 'repair_attempts', ['task_id'], unique=False)
    op.create_table('tasks',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_agent_id', sa.String(length=64), nullable=True),
    sa.Column('owner_manager', sa.String(length=200), nullable=True),
    sa.Column('worker_type', sa.String(length=200), nullable=True),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('requirement_ids', sa.JSON(), nullable=False),
    sa.Column('depends_on_task_ids', sa.JSON(), nullable=False),
    sa.Column('expected_outputs', sa.JSON(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.String(length=16), nullable=False),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('result_success', sa.Boolean(), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('result_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('result_logs', sa.Text(), nullable=True),
    sa.Column('result_error_message', sa.Text(), nullable=True),
    sa.Column('result_duration_seconds', sa.Float(), nullable=True),
    sa.Column('result_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_tasks_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index('ix_tasks_project_status', 'tasks', ['project_id', 'status'], unique=False)
    op.create_table('test_results',
    sa.Column('test_id', sa.String(length=64), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('module_id', sa.String(length=64), nullable=True),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('ran_at', sa.DateTime(), nullable=False),
    sa.Column('report_lint_passed', sa.Boolean(), nullable=True),
    sa.Column('report_type_check_passed', sa.Boolean(), nullable=True),
    sa.Column('report_coverage_percent', sa.Float(), nullable=True),
    sa.Column('report_summary', sa.Text(), nullable=True),
    sa.Column('report_generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('fk_test_results_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('test_id', name=op.f('pk_test_results'))
    )
    op.create_index(op.f('ix_test_results_project_id'), 'test_results', ['project_id'], unique=False)
    op.create_index(op.f('ix_test_results_report_id'), 'test_results', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_results_report_id'), table_name='test_results')
    op.drop_index(op.f('ix_test_results_project_id'), table_name='test_results')
    op.drop_table('test_results')
    op.drop_index('ix_tasks_project_status', table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_repair_attempts_task_id'), table_name='repair_attempts')
    op.drop_index(op.f('ix_repair_attempts_project_id'), table_name='repair_attempts')
    op.drop_table('repair_attempts')
    op.drop_index(op.f('ix_llm_requests_project_id'), table_name='llm_requests')
    op.drop_index(op.f('ix_llm_requests_created_at'), table_name='llm_requests')
    op.drop_table('llm_requests')
    op.drop_index(op.f('ix_events_project_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_errors_project_id'), table_name='errors')
    op.drop_table('errors')
    op.drop_index(op.f('ix_deployment_runs_project_id'), table_name='deployment_runs')
    op.drop_index(op.f('ix_deployment_runs_created_at'), table_name='deployment_runs')
    op.drop_table('deployment_runs')
    op.drop_index(op.f('ix_contracts_project_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_index(op.f('ix_artifacts_project_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_architecture_decisions_project_id'), table_name='architecture_decisions')
    op.drop_table('architecture_decisions')
    op.drop_index(op.f('ix_agents_project_id'), table_name='agents')
    op.drop_table('agents')
    op.drop_table('projects')
    # ### end Alembic commands ###
